### ISSUE TITLE
Adding extra tidalcycles.sounds.paths has a long delay before showing in the sound browser

### ISSUE THREAD

**Issue by cleary** [tidalcycles/vscode-tidalcycles#29]
Hi, 
Thanks for the plugin, the sound browser is a killer feature (imo). 
The default Dirt-Samples path works really well, but when I add extra sample paths, they don't appear in the sound browser.

Double and triple checked syntax according to the reference doc, and variations on the location of the comma, my settings section currently looks like:

```
"tidalcycles.sounds.paths": [
        "/home/bernie/.local/share/SuperCollider/downloaded-quarks/Dirt-Samples/"
        , "/home/bernie/Music/Samples/Tidal_Club/samples-extra/"
    ]
```

The path definitely exists:

```
$ ls -l /home/bernie/Music/Samples/Tidal_Club/samples-extra/
total 92
drwxrwxr-x 2 bernie bernie  4096 Aug 29  2019 break
drwxrwxr-x 2 bernie bernie  4096 Aug 29  2019 bsbass
drwxrwxr-x 2 bernie bernie  4096 Aug 29  2019 bsguitar
...
```

TidalCycles for VSCode version: 1.4.1

VS Code About:

```
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T11:22:13.689Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-45-lowlatency
```

There's some discussion on the [club tidalcycles forum](https://club.tidalcycles.org/t/vscode-extension-sound-browser-not-loading-the-sample-packs-for-me/394/10) (if you have access) and had a Windows 10 user confirm the same problem

**Comment by cleary** [comment]
OK, strange thing happened - I left my computer overnight (suspended, didn't restart vscode), and the additional path happened to be in the sound browser?

I restarted the browser, and reloaded the extensions several times trying to make it work but without any luck - is there a delay on it's application?

**Comment by kindohm** [comment]
@cleary I'm not aware of a delay, intentional or otherwise. I don't use the feature very often but I have a couple of paths configured and they show up. I haven't tried to reproduce this problem yet.

**Comment by cleary** [comment]
All good Mike, at this stage I'm doubting myself - I was pretty thorough about checking though.

Please feel free to close
