### ISSUE TITLE
Could not find module 'Sound.Tidal.Context'

### ISSUE THREAD

**Issue by tillmanjex** [tidalcycles/vscode-tidalcycles#32]
After installing everything via the ```curl``` install script on the TidalCycles website and installing the VS code extension, I get this error when trying to evaluate a line:

GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Prelude> Prelude> Warning: GHCi | 
Warning: GHCi | <no location info>: error:
Warning: GHCi |     Could not find module ‘Sound.Tidal.Context’
Warning: GHCi |     It is not a module in the current program, or in any known package.

I also get this warning:
Configured GHCI path was not found: ghci

I know I may well need to input the location in my PATH, but I can't find any direction on where to find the ghci file.
I've tried setting in vs code json settings: ```"tidalcycles.ghciPath" : "ghci"``` but it didnt work.

Any help would be great.

**Comment by yaxu** [comment]
Hi @tillmanjex, it seems your editor is configured fine, and haskell is loading, but somehow the tidal library itself is missing. You can install it from a commandline in a terminal window with these commands:
```
cabal v1-update
cabal v1-install tidal
```

**Comment by tillmanjex** [comment]
Hi @yaxu . So the builds are failing for some reason. 
I've attached a txt file with the full terminal output. 
It didnt actually like ```v1-update``` and suggested I tried ```v2-update``` which I did. 
It did however accept both ```v1* and v2-install tidal``` but both resulted in build errors. 

[buildfail.txt](https://github.com/tidalcycles/vscode-tidalcycles/files/8534065/buildfail.txt)

**Comment by tillmanjex** [comment]
installing llvm via homebrew now (not sure if it was included in the main install...) and will try again then report back

**Comment by tillmanjex** [comment]
no luck @yaxu . still getting the same errors as in the original file.

**Comment by yaxu** [comment]
I'm not a mac user so can't help too much. Have a search on the forum for `llvm`, maybe a few fellow travellers might have the same issue there: https://club.tidalcycles.org/

**Comment by tillmanjex** [comment]
fixed it and made a post for others if needed. 
It came down to mac not seeing the native llvm install as well as clang compilation problems, that I think stemmed from an clang target / architecture missmatch.
https://club.tidalcycles.org/t/apple-silicon-llvm-clang-installation-issues-fix/4018
